#!/usr/bin/env python3
"""从 permissions/permissions.json 生成后端与前端权限常量（产物提交入库）。

Run: python tools/gen_permissions.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "permissions" / "permissions.json"
BACKEND_OUT = ROOT / "backend" / "app" / "permissions" / "_generated.py"
FRONTEND_OUT = ROOT / "frontend" / "src" / "constants" / "permissions.generated.ts"


def load():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    roles = data["roles"]
    perms: dict[str, list[str]] = {}
    policies: dict[str, str] = {}
    for name, val in data["permissions"].items():
        if isinstance(val, list):
            perms[name] = val
        else:
            perms[name] = val["roles"]
            if val.get("object_policy"):
                policies[name] = val["object_policy"]
    return roles, perms, policies


def render_backend(roles, perms, policies) -> str:
    lines = [
        "# AUTO-GENERATED by tools/gen_permissions.py — DO NOT EDIT BY HAND.",
        "from __future__ import annotations",
        "",
        f"ROLES: list[str] = {json.dumps(roles, ensure_ascii=False)}",
        "",
        "PERMISSIONS: dict[str, list[str]] = {",
    ]
    for name in sorted(perms):
        lines.append(f"    {json.dumps(name)}: {json.dumps(perms[name], ensure_ascii=False)},")
    lines += ["}", "", "OBJECT_POLICIES: dict[str, str] = {"]
    for name in sorted(policies):
        lines.append(f"    {json.dumps(name)}: {json.dumps(policies[name])},")
    lines += ["}", ""]
    return "\n".join(lines)


def render_frontend(roles, perms, policies) -> str:
    names = sorted(perms)
    union = " | ".join(json.dumps(n) for n in names) or "never"
    lines = [
        "// AUTO-GENERATED by tools/gen_permissions.py — DO NOT EDIT BY HAND.",
        "",
        f"export type Role = {' | '.join(json.dumps(r) for r in roles)};",
        f"export type Permission = {union};",
        "",
        "export const PERMISSIONS: Record<Permission, Role[]> = {",
    ]
    for name in names:
        roles_ts = "[" + ", ".join(json.dumps(r) for r in perms[name]) + "]"
        lines.append(f"  {json.dumps(name)}: {roles_ts},")
    lines += ["};", ""]
    return "\n".join(lines)


def build() -> tuple[str, str]:
    roles, perms, policies = load()
    return render_backend(roles, perms, policies), render_frontend(roles, perms, policies)


def main():
    backend_txt, frontend_txt = build()
    BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    FRONTEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    BACKEND_OUT.write_text(backend_txt, encoding="utf-8", newline="\n")
    FRONTEND_OUT.write_text(frontend_txt, encoding="utf-8", newline="\n")
    print(f"Wrote {BACKEND_OUT}")
    print(f"Wrote {FRONTEND_OUT}")


if __name__ == "__main__":
    main()
